version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
           command: |
             git config --global user.email "circleci@circleci.com"
             git config --global user.name "CircleCI"
             git submodule update --init --recursive
             rm -rf public/
             git worktree add -B master public origin/master
       - run: docker run --rm -v $PWD:/src -v $PWD/public:/output -e HUGO_WATCH=false jojomi/hugo
       - run: cd public && git add --all && git commit -m Publishing ; cd .. ; git push origin master
